### ISSUE TITLE
Automatically update

### ISSUE THREAD

**Issue by nghiabros** [CYFARE/HellFire#1]
Hi buddy, 
I am using the newest version. Could you add automatically update feature for the next version?

**Comment by nghiabros** [comment]
hope the script coming soon,
thank you!

**Comment by ktpttd** [comment]
yes, please coming soon

**Comment by CYFARE** [comment]
Guys, please check the latest release & I've created an installer shell script for GNU/Linux. Also go through the readme for steps. For Windows, the same exe installer will update/upgrade your browser without changing any settings/bookmarks/etc. :)

**Comment by CYFARE** [comment]
Abandoned due to overheads and conflict of core structure of not adding additional background workers or binaries to the main source, making sure the original source and logic remain 1:1 with Mozilla's branch.
